### ISSUE TITLE
buttonImageInput active button should be handled in the frontend with JS

### ISSUE THREAD

**Issue by jpmarindiaz** [datasketch/shinyinvoer#25]
This shoud be done in JS not in R
```
  actual_but <- reactiveValues(active = 'bar')

  observe({
    viz_rec <-  c("bar", "line", "pie", "donut", "treemap", "bubbles")
    if (is.null(viz_rec)) return()
    if (is.null(input$viz_selection)) return()
    if (!( input$viz_selection %in% viz_rec)) {
      actual_but$active <- viz_rec[1]  
    } else {
      actual_but$active <- input$viz_selection
    }
  })
```

**Comment by brazadas** [comment]
@jpmarindiaz @ddazal esto ya está ¿cierto?

**Comment by jpmarindiaz** [comment]
Ni idea, por fa revisa tu en el código si se hizo o no, yo no lo hice

**Comment by brazadas** [comment]
me parece que eso es parte de un shiny app -- entonces ni siquiera entiendo el issue bien. La parte de asignar cuál botón está activo en el buttonImageInput está escrita en JS.

**Comment by ddazal** [comment]
@brazadas Yo tampoco entiendo bien de que va el issue, pero si dices que ya está implementado en JS cierro el issue. Cualquier cosa lo volvemos a abrir

**Comment by jpmarindiaz** [comment]
Si todas las apps que hacemos tienen ese bloque de código entonces este issue se mantiene abierto. Si ya está implementado en el JS está bien cerrarlo. Eso lo que hace es actualizar los botones de las imágenes para cambiar que salgan activas o no

**Comment by brazadas** [comment]
Ninguna de las apps tiene ese bloaque; como dije antes, la parte de actualizar los botones activos o no está en js, entonces, creo que se puede cerrar
