### ISSUE TITLE
add colorPalette input label ans better styles

### ISSUE THREAD

**Issue by brazadas** [datasketch/shinyinvoer#26]
Margin, padding... the function doesn't have label parameter which might be useful
![Screenshot from 2020-05-06 20-22-51](https://user-images.githubusercontent.com/19413995/81244329-bd9ac980-8fd7-11ea-90ff-b3d02f84c0ba.png)
![Screenshot from 2020-05-06 20-26-05](https://user-images.githubusercontent.com/19413995/81244369-dc995b80-8fd7-11ea-9e38-29a1a56c89bb.png)

**Comment by jpmarindiaz** [comment]
Added label parameter in f21c9c6
Still need to fix styles @ddazal

**Comment by ddazal** [comment]
Is it 165af9bb5bf66c249dc00c425e4fdd1bbc13c647 enough to close this issue?

**Comment by brazadas** [comment]
@ddazal shiny's input containers have _.form-group_ class that has a 13px  _margin-bottom_ 
![Screenshot from 2020-06-21 18-31-34](https://user-images.githubusercontent.com/19413995/85237616-d7f4ff00-b3ed-11ea-8f2e-d8af8590bb37.png)
maybe this could be good too for colorPalette input?

**Comment by ddazal** [comment]
Yes! Coming on next commit
