### ISSUE TITLE
colorPaletteInput: Hide close (x) and add (+) buttons when not needed

### ISSUE THREAD

**Issue by jpmarindiaz** [datasketch/shinyinvoer#30]
If n_max color is reached remove or disable (+) button.

When the number of colors is fixed (need to add a new parameter for this) remove (x) and (+) buttons.
Do we need a min_colors too? If so, make sure to remove the remove color button (x) when the minimum number of colors is reached.

**Comment by ddazal** [comment]
Add button is disabled (with a native html attribute) when the n_max is reached though it's lacking styles @marianaviro . The discussion for fixed colors and min_colors should take place on independent issues.

Let's use this thread to define if we add styles to the button when disabled or if we remove it.
