### ISSUE TITLE
add n_grid (number of imaged per row) parameter to buttonImageInput

### ISSUE THREAD

**Issue by brazadas** [datasketch/shinyinvoer#31]
for an easy control of how many images per row
![Screenshot from 2020-06-09 10-34-43](https://user-images.githubusercontent.com/19413995/84168304-debe6200-aa3c-11ea-9bea-f2b1ab8ac7f6.png)
![Screenshot from 2020-06-09 10-34-11](https://user-images.githubusercontent.com/19413995/84168308-dfef8f00-aa3c-11ea-827a-b9250a7143c1.png)

**Comment by jpmarindiaz** [comment]
Add `ncol` or `nrow` parameter. When both are NULL it should be the current behavior, which I think simply arranges them automaticaly given available space.

For the case of showing document thumbnails I think you can control them by setting a fixed width of the panel and a bit smaller image width

**Comment by brazadas** [comment]
we talk about it with @CamilaAchury; there are two properties _grid-gap_ and _grid-template-columns_ that control the number of images per row and the space between them. This should be easily modified from the arguments of the function. 
We proposed an n_grid argument that indicates how many images per row (it automatically fits the width of the contatiner) and let the gap between them be fixed (20px); if the argument is null then the default behaviour would be the current one that gives every image a 60px width and fits as many as possible per row.
Also, in this function there are only class arguments for modifying the styles of not selected items and for the image container itself. This implies that to use this arguments (say to change non-selected images' style) we would have to manually add the classes to the css of the HTML; we talked about defining specific arguments for this (color of non-selected, ...) or to include styles argument to the function and pass it directly inline to the HTML tag or to leave it like it is 
what do you think @jpmarindiaz?

**Comment by jpmarindiaz** [comment]
I would still go for `ncol` or `nrow`, this is how it is named in other functions and packages,  independent on the classes names or whatever happens behind the scenes. 
`ngrid` doesn't say much about what it does, it is actually the number of columns (i.e. how many images per row) so I would call it `ncol`, and add the other `nrow` for users to fixe one or the other.

It would be good to add some color border or something like that for the selected images. Users of the function should never care about class names, only sensible parameter names, they do not need to know HTML to use the function

**Comment by brazadas** [comment]
ok yes.
if ncol is set then it determines nrow, so i think we should leave only ncol

**Comment by jpmarindiaz** [comment]
No, both. Users use one or the other.

if `ncol = 1` they get this
![image](https://user-images.githubusercontent.com/1489570/84180883-dae70b80-aa4d-11ea-8530-746f51d0a454.png)

if `nrow = 2` they get this
![image](https://user-images.githubusercontent.com/1489570/84180927-eb978180-aa4d-11ea-996f-26151027f80a.png)

We don't want users to calculate numbers in their heads so they can use the function

**Comment by brazadas** [comment]
ok
