### ISSUE TITLE
Add param to fix a number of colors [colorPaletteInput]

### ISSUE THREAD

**Issue by ddazal** [datasketch/shinyinvoer#37]
Taken from #30 

> When the number of colors is fixed (need to add a new parameter for this) remove (x) and (+) buttons.

Do I work on this?

**Comment by brazadas** [comment]
if you define the _n_ fixed colors and set the max_colors parameter to _n_ you get _n_  and only _n_ colors
`colorPaletteInput("c0", "Color", colors = c("red", "purple"), max_colors = 2)`
so there is a _way_  now to get fixed number of colors without the parameter; is this too tricky --rebuscado @ddazal?

**Comment by ddazal** [comment]
It's a nice workaround. But still you can remove a color from the UI, can't you? I think the idea behind this issue is to keep a fixed number of color choices around so the user can **only** change their values. I'm not sure though. Could you explain us further @jpmarindiaz ?

**Comment by jpmarindiaz** [comment]
It's fine. We can close this now. @brazadas make sure it is documented in the function
