### ISSUE TITLE
Label option for toggleSwitchInput

### ISSUE THREAD

**Issue by brazadas** [datasketch/shinyinvoer#41]
In particular times it could be useful to have a label that describes for what the toggle switch stands for

**Comment by jpmarindiaz** [comment]
Can you add this yourself? it should'nt be difficult

**Comment by brazadas** [comment]
yes; should it lay on top or to the right-left?

**Comment by jpmarindiaz** [comment]
Leave it as all the other, I believe they are on top of the input
