### ISSUE TITLE
dropdownActionInput does not work well with other outputs (highcharts, visNetwork) and inputs (colorPaletteInput)

### ISSUE THREAD

**Issue by brazadas** [datasketch/shinyinvoer#42]
when using dropdownActionInput in shinyapp other outputs (such as highcharts, visNetwork) and even inputs (colorPaletteInput) do not work well
![Screenshot from 2020-07-08 17-33-03](https://user-images.githubusercontent.com/19413995/86977365-0f7bdf00-c142-11ea-9e79-9f233a41ba01.png)
![Screenshot from 2020-07-08 17-39-00](https://user-images.githubusercontent.com/19413995/86977368-10ad0c00-c142-11ea-84c8-86deccc3fa47.png)
@CamilaAchury 
@ddazal 
@jpmarindiaz

**Comment by jpmarindiaz** [comment]
Please put a reproducible example of an app that shows this issue so @ddazal can replicate and see what's happening

**Comment by brazadas** [comment]
Yes; when making the reproducible example I notice that it actually works with visNetwork (the problem was the value saved for color inputs that were passed as parameters for visNetwork). What does not work is the colorPaletteInput and the dropdownActionInput simultaneously:
```
library(shiny)
library(shinyinvoer)

ui <- fluidPage(
  dropdownActionInput("dropdown", "Dropdowner", c("W" = "w", "E" = "e")),
  colorPaletteInput("color", "Color", colors = "#234ef4"),
)

server <- function(input, output, session) {
  
}

shinyApp(ui, server)
```
If the dropdown is first, the color palette does not work well; if color palette is first, the dropdown does not show

**Comment by ddazal** [comment]
> Yes; when making the reproducible example I notice that it actually works with visNetwork (the problem was the value saved for color inputs that were passed as parameters for visNetwork). What does not work is the colorPaletteInput and the dropdownActionInput simultaneously:
> 
> ```
> library(shiny)
> library(shinyinvoer)
> 
> ui <- fluidPage(
>   dropdownActionInput("dropdown", "Dropdowner", c("W" = "w", "E" = "e")),
>   colorPaletteInput("color", "Color", colors = "#234ef4"),
> )
> 
> server <- function(input, output, session) {
>   
> }
> 
> shinyApp(ui, server)
> ```
> 
> If the dropdown is first, the color palette does not work well; if color palette is first, the dropdown does not show

@brazadas I think  `colors` param on `colorPaletteInput` function receives a vector even if it is a single color.

```R
colorPaletteInput("color", "Color", colors = c("#234ef4"))
```
Please run the app with this change to see if it works before I dig into it.

**Comment by ddazal** [comment]
Please pull the last commit and provide some feedback about what isn't working. Otherwise, close this issue. @brazadas @CamilaAchury
