### ISSUE TITLE
TextInput with active button

### ISSUE THREAD

**Issue by CamilaAchuri** [datasketch/shinyinvoer#60]
es importante hacer un textInput acompañado de un botón de activación, con la finalidad de que solo se renderize el texto cuando 
se de click en el botón

**Comment by jpmarindiaz** [comment]
O dándole Enter también

**Comment by CamilaAchuri** [comment]
Si también

**Comment by CamilaAchuri** [comment]
Entonces tal vez debería tener la opción de un Boolean para añadar o no el botón, y si es FALSE, no se añade pero solo renderiza al dar enter

**Comment by ddazal** [comment]
@CamilaAchury verifica que funcione como es esperado.
