### ISSUE TITLE
create radioButton input with HTML

### ISSUE THREAD

**Issue by CamilaAchuri** [datasketch/shinyinvoer#69]
crear un input donde se puedan ingresar listas de paletas de colores y cuya respuesta en Shiny sea el nombre de  la lista de color.
Eg:
<img width="251" alt="image" src="https://user-images.githubusercontent.com/17035597/156036257-e1a6ee2b-8679-4859-8551-e9baf156b9d7.png">
Entonces, supongamos que el id de la primer selecciones es "List_color_1",  al seleccionar esta el print en Shiny debería ser  "List_color_1" o la paleta de colores de esa lista.

**Comment by CamilaAchuri** [comment]
es importante que no se pueda elegir color como en el actual input de colores, que al dar click en el 
cuadrado aparece el color picker.

**Comment by jpmarindiaz** [comment]
En realidad antes que un input de paleta de colores es un radioButton con imágenes.
Al final no importa si son coloroes o logos, lo que retorna en un string a partir de una imagen que está en un radio botón

**Comment by CamilaAchuri** [comment]
radioButtonsHTML(inputID, label, choices = list(a = "<img>logo1</img>", b = "<img>logo2</img>"), class = NULL, selected)

hacer update

**Comment by CamilaAchuri** [comment]
Con html, así se pueden agregar no solo imágenes, si no cualquier cosa requerida

**Comment by ddazal** [comment]
@CamilaAchuri por favor revisa los cambios hechos en 4b53481715ae54146647b26ac38c1c71173ac331. El input tiene un nombre diferente, `radioButtonsInput`. Si necesita llamarse `radioButtonsHTMLInput` abre un nuevo PR.
