### ISSUE TITLE
add dateInput 

### ISSUE THREAD

**Issue by CamilaAchuri** [datasketch/shinyinvoer#70]
Añadir input de fechas con opción para rango 

![image](https://user-images.githubusercontent.com/17035597/160475646-fc1ff0a5-2e21-444d-b304-caf4f8ec2be5.png)

 o valor unico 

Al poner la manita en una caja que salga el calendario, donde el input tenga la opción de ver por años, por mes, por días.

dias:
<img width="179" alt="image" src="https://user-images.githubusercontent.com/17035597/160476063-60244dd3-f991-4136-89c2-b1e715df9b93.png">

meses:
<img width="246" alt="image" src="https://user-images.githubusercontent.com/17035597/160476155-058b9fcb-8ed2-4d06-a9bb-3559aafa2cc3.png">

años, igual que el de meses, pero en las cajitas con los años.

**Comment by ddazal** [comment]
@CamilaAchuri por favor revisa el input. Los parámetros relevantes son los siguientes, en formato `yyyy-mm-dd`:

`start`: Fecha por defecto del inicio del rango
`end`: Fecha por defecto del fin del rango
`min`: Fecha mínima que se puede seleccionar
`max`: Fecha máxima que se puede seleccionar
